---
- name: Install Microshift
  become: true
  ansible.builtin.yum:
    name: microshift
    state: present

- name: Copy pull-secret to node
  become: true
  ansible.builtin.copy:
    content: "{{ openshift_pull_secret }}"
    dest: "{{ registry_secret_path }}"
    owner: root
    group: root
    mode: '0600'
  no_log: "{{ hide_sensitive_logs }}"

- name: Change Microshift configuration files
  become: true
  ansible.builtin.copy:
    content: |
      {{ lookup('vars', item.var_name) | to_nice_yaml(indent=2) }}
    dest: "/etc/microshift/{{ item.dest }}"
    mode: "0644"
    owner: root
    group: root
  loop:
    - var_name: microshift_config
      dest: config.yaml
    - var_name: microshift_lmvd
      dest: lvmd.yaml
  when: vars[item.var_name]
  register: microshift_config

- name: Restart Microshift if config changed
  become: true
  ansible.builtin.systemd:
    name: microshift
    state: restarted
  when: microshift_config is changed

- name: Ensure Microshift started and enabled
  become: true
  ansible.builtin.systemd:
    name: microshift
    state: started
    enabled: true
