---
- name: Create directory for /var/lib/microshift
  become: true
  ansible.builtin.file:
    path: /var/lib/microshift
    state: directory
    mode: 0700
    owner: root
    group: root

- name: Mount ramdisk
  become: true
  ansible.posix.mount:
    src: tmpfs
    name: /var/lib/microshift
    fstype: tmpfs
    state: mounted
    opts: "defaults,size={{ ramdisk_size }}"

- name: Set proper permissions after mount
  become: true
  ansible.builtin.file:
    path: /var/lib/microshift
    state: directory
    mode: 0700
    owner: root
    group: root

- name: Set proper SELinux context
  become: true
  ansible.builtin.command: restorecon -F /var/lib/microshift
