---
- name: Copy script to verify deployment
  ansible.builtin.copy:
    src: wait-for-microshift.sh
    dest: /tmp/wait-for-microshift.sh
    mode: "0755"

- name: Check if all containers are up and ready
  ansible.builtin.command: /tmp/wait-for-microshift.sh
  changed_when: true
  register: _microshift_svc_status
  ignore_errors: true

- name: Print all resources when wait for microshift fail
  ansible.builtin.command: oc get all --all-namespaces
  when: _microshift_svc_status.rc == 1

- name: Check once again if all containers are up
  ansible.builtin.command: /tmp/wait-for-microshift.sh
  changed_when: true
