---
- name: Disable dnsmasq service
  become: true
  ansible.builtin.systemd:
    name: dnsmasq
    state: stopped
    enabled: false

- name: Reload NetworkManager
  become: true
  ansible.builtin.systemd:
    name: NetworkManager
    state: reloaded
    enabled: true

- name: Restart Openshift DNS
  ansible.builtin.shell: |
    kubectl -n openshift-dns rollout restart daemonsets dns-default
